### ISSUE TITLE
install issues and updates after install

### ISSUE THREAD

**Issue by paigestormblade** [kubuntu-team/kubuntu-manual#1]
post removed based on unappropriated section by creator. hes right not the place for the section that was originally posted on.  maybe we can go off at a company that don't know how to summarize proper posting section meant for developer awareness...

**Comment by ahoneybun** [comment]
This is the manual for Kubuntu not the project itself so it's not the correct place for this report.

**Comment by paigestormblade** [comment]
This post has been added to the company with Bradly, this needed to be placed as it is important for the makers of kubuntu. This type of act is not suitable for the work of kubuntu thus why it's always messed up because of people like you, this post was suitable for the are as it did state such, and could have been placed else where since your a male egotistic thinking woman don't belong it really shows on your part., but as me being highly skilled more so then most wanna be developers as a woman, your a male ego acting as if my post isn't worthy for development. But soon you will find as a partner to the company we will not support kubuntu due to is sloppy work i disband my self from people who cant play on the playground as a team instead to shove important details aside bad for business. so because of you attitude we will not support kubuntu products as it is always crapped up, you never fix the real issues you have not fixed none since early versions, and this just proves why they don't get fixed. i will how ever place it so people are aware of the sloppy works that get placed in to something like kubnuntu i dont want to have to keep supporting issues it always has. and i made sure as a partner that kubuntu is always a trashy system as well based on my input you refused to work with me as a long time partner of the main company.
