### ISSUE TITLE
Manual document header says "Release release" instead of "Release <release number>"

### ISSUE THREAD

**Issue by nerdfever** [kubuntu-team/kubuntu-manual#10]
I mean https://github.com/kubuntu-team/kubuntu-manual/releases/tag/v22.04.1

**Comment by ahoneybun** [comment]
Thank you for the bug reports! This one should be fixed in the kubuntu-22.04-LTS branch though no release yet as there isn't 22.04.2 of that release yet. It should have been today but looks like it is now 2/23/23:

https://www.omgubuntu.co.uk/2023/01/ubuntu-22-04-2-point-release-delay
