### ISSUE TITLE
Activities section never explains what an "Activities" is

### ISSUE THREAD

**Issue by nerdfever** [kubuntu-team/kubuntu-manual#13]
Similar to the issue re the Panel section, in 3.2.5 of the "Activities" section of https://github.com/kubuntu-team/kubuntu-manual/releases/tag/v22.04.1 talks a lot about Activities, but never stops to explain what they are.

Somewhere in this section there should be a sentence that goes something like "Activities are [description goes here]". There isn't.

What I know about Activities from reading the section as it currently is:

- They are exclusive to KDE
- They're often misunderstood
- The manual promises to explore what they are, how to set them up, how to use them
- They provide a slick way to setup and configure environments

That's all nice to know. But what _are_ they? This is not mentioned. I still don't know what they are.

**Comment by nerdfever** [comment]
Suggested text: "An Activity is a separate desktop, complete with it's own set of icons (and their placement), wallpaper, theme, widgets, and other customization".

This assumes that I correctly understand what it is ...I may not. It also assumes that the preferred term is "widgets" and not "plasmoids" (I suggest standard terms are always better than invented names when possible, but even more strongly - pick just one term and stick with it. It'll reduce a lot of confusion.)

While I'm at it, I note that the order of Activities changes each time you switch Activities. I think it's sorting by recency of use.

This is neither expected nor obvious nor (IMHO) useful. As a general rule, it's best to leave things where they were (so the user has some idea where to look for them next time), unless the user explicitly moves them, or chooses a sort order. Hidden and unexpected sort orders are Bad Things.

**Comment by ahoneybun** [comment]
I used your suggested text as you are correct about this feature.
