### ISSUE TITLE
Change "Plasmoids" to "Widgets"

### ISSUE THREAD

**Issue by nerdfever** [kubuntu-team/kubuntu-manual#15]
Re the 22.04.1 LTS manual:

Per https://userbase.kde.org/Plasma#Widgets, it seems "widgets" is the currently preferred term, with "plasmoids" apparently deprecated.

I think that was wise - if an existing well-known term will do, it's better to use it than to invent a new one.

Regardless of the wisdom of the change, the manual should track current usage. So

* 3.2.3 should be titled "Widgets"
* First line of that should read "Widgets (previously called Plasmoids)...." (this follows wording in the above-referenced page)

**Comment by ahoneybun** [comment]
Fixed: https://github.com/kubuntu-team/kubuntu-manual/commit/67e116683849243c4bf04b954f6c23bae8b3c64f
