### ISSUE TITLE
Drivers section

### ISSUE THREAD

**Issue by nerdfever** [kubuntu-team/kubuntu-manual#16]
Re the 22.04.1 LTS manual:

The Drivers section doesn't have a section number of it's own, it just follows from an extended discussion of Activities.

It should be 3.3 or 3.2.8.

The first paragraph is confusingly drafted and has typos and misspellings.

Current text:

On every Operating System (Windows, macOS, and Linux) there are programs called Drivers which you install on
your computer. These Drivers let your computer use new hardware or existing hardware, like Wi-Fi. There Drivers
also cover your graphics card e.g NVIDIA, AMD, sometimes the nonfree or restricted drivers let the cards perform
better than the free ones. The ‘Additional Drivers’ section of Disocver handles installing and uninstalling these for you.
These improvements may cover gaming, video editing and processing to image editing.

Suggested replacement:

On every operating system (Windows, macOS, and Linux) there are programs called Drivers which let your computer work with specific hardware components, such as Wi-Fi interfaces, graphics cards (nVidia, AMD...), etc. Sometimes nonfree or restricted Drivers let the hardware perform better than the free Drivers that come with Kubuntu. These improvements may cover gaming, video editing and processing to image editing. 

The ‘Additional Drivers’ section of the Discover program handles installing and uninstalling these nonfree or restricted Drivers for you.

**Comment by nerdfever** [comment]
Additonal issues in this Drivers section:

* Image on page 24 doesn't match what's in the distribution.

Image: "Ubuntu jammy jellyfish (development branch)"
Distro: "Ubuntu 22.04.1.LTS"

* Just under the image, step 2 says "2. Select Settings then left-click the ‘Software Sources’ button to the right of ‘Ubuntu Jammy Jellyfish’"

It should refer to "Ubuntu 22.04.1. LTS".

Also, the "button" does not appear as a button unless you hover the mouse over it. So a new user may have trouble finding it, since it doesn't look like a button.

**Comment by ahoneybun** [comment]
@nerdfever where are you getting the numbers such as 3.3 or 3.2.8 from?

**Comment by ahoneybun** [comment]
The newest commit should help with most of this, thanks!

**Comment by nerdfever** [comment]
@ahoneybun The numbers are in the PDF. I've looked only at the PDF.
