### ISSUE TITLE
Can not download kubuntu 22.04

### ISSUE THREAD

**Issue by jaimesouza** [kubuntu-team/kubuntu-manual#18]
Hello, 

I can not download kubuntu in https://cdimage.ubuntu.com/kubuntu/releases/22.04.1/release/kubuntu-22.04.1-desktop-amd64.iso

```
Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at cdimage.ubuntu.com Port 443
```

**Comment by ahoneybun** [comment]
@jaimesouza it looks like this is about the Kubuntu website is that correct?

**Comment by ahoneybun** [comment]
It looks like it is the website and it is because the 22.04.2 release is now out so I'll update the site, thanks @jaimesouza !

**Comment by ahoneybun** [comment]
Fixed!

**Comment by jaimesouza** [comment]
Alright! Thank you @ahoneybun!
