### ISSUE TITLE
EPub issue not synchronized with the PDF issue

### ISSUE THREAD

**Issue by blueboy90780** [kubuntu-team/kubuntu-manual#6]
On https://github.com/kubuntu-team/kubuntu-manual/releases/tag/v22.04.0 release. The EPUB release seems to lag behind by the PDF release. At the end of the introductory page, the manual indicates it's for 20.04 rather than the latest 22.04 LTS release.

I don't mind switching to PDF, but since the team releases 2 different formats at a time. I thought it would be good to point out for those who prefer EPUB versions over .PUB versions for reading.

**Comment by ahoneybun** [comment]
Fixed in latest release!
