### ISSUE TITLE
"Launchers" section is confusing

### ISSUE THREAD

**Issue by nerdfever** [kubuntu-team/kubuntu-manual#9]
In the 22.04 LTS manual, the "Launchers" section (3.1.1):

1 - Discusses Kickoff, but Kickoff seems to describe itself as "Application Launcher - Plasma", which conflicts with the name "Kickoff". It would be far less confusing for new users if the names used in the manual matched the names used in the UI.

2 - The next page (still in 3.1.1) discusses "Application Dashboard", then "Application Menu", then "Krunner", without ever making it clear that these are not _part of_ Kickoff, but (I think) alternatives to it. (I'm sure this is obvious to the authors. It was not obvious to me.)

**Comment by ahoneybun** [comment]
I've made some changes that should address this feedback, thoughts @nerdfever ?
